const mongose = require("mongoose")
const express = require("express")
const app = express()
const bodyParser= require("body-parser")
var server = require("http").Server(app);
var io = require("socket.io")(server)
require('./middlleware/socket')(io)
const port = process.env.PORT || 2000;
mongose.connect(process.env.MONGO_URL,
{useNewUrlParser:true, useUnifiedTopology:true, useCreateIndex:true}).then(db => console.log("connectSucces"))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use(express.static('public'))
const memberRouter= require("./routers/member")
const userRouter= require("./routers/user")
const topicRouter = require("./routers/topic")
const levelRouter = require("./routers/level")
const questionRouter = require("./routers/question")
const testRouter = require("./routers/test")
const examYearRouter = require("./routers/examYear")
const examTestRouter = require("./routers/examTest")
const RTRSRouter = require("./routers/rating&resuilt")
app.use('/',memberRouter)
app.use('/',userRouter)
app.use('/',topicRouter)
app.use('/',levelRouter)
app.use('/',questionRouter)
app.use('/',testRouter)
app.use('/',examYearRouter)
app.use('/',examTestRouter)
app.use('/',RTRSRouter)
server.listen(port,function(){
    console.log("success"+port)
})
